services:
  db:
    image: postgres:latest
    container_name: my-postgres-db
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports: ["5432:5432"]
    volumes: ["postgres-data:/var/lib/postgresql/data"]
volumes:
  postgres-data:
